//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JamZoo.Project.WebSite.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class coal50
    {
        public int yr_mnth { get; set; }
        public int row_no1 { get; set; }
        public Nullable<double> fc { get; set; }
        public Nullable<double> mk { get; set; }
        public Nullable<double> mq { get; set; }
        public Nullable<double> sa { get; set; }
        public Nullable<double> nu { get; set; }
        public Nullable<double> ed { get; set; }
        public Nullable<double> ff { get; set; }
        public Nullable<double> ai { get; set; }
        public Nullable<double> fss { get; set; }
        public Nullable<double> fh { get; set; }
        public Nullable<double> am { get; set; }
        public Nullable<double> pb { get; set; }
        public Nullable<double> mz { get; set; }
        public Nullable<double> pa { get; set; }
        public Nullable<double> aj { get; set; }
        public Nullable<double> my { get; set; }
        public Nullable<double> ab { get; set; }
        public Nullable<double> np { get; set; }
        public Nullable<double> fn { get; set; }
        public Nullable<double> na { get; set; }
        public Nullable<double> ms { get; set; }
        public Nullable<double> fl { get; set; }
        public Nullable<double> ek { get; set; }
        public Nullable<double> mu { get; set; }
        public Nullable<double> au { get; set; }
        public Nullable<double> ea { get; set; }
        public Nullable<double> en { get; set; }
        public Nullable<double> fo { get; set; }
        public Nullable<double> aa { get; set; }
        public Nullable<double> fs { get; set; }
        public Nullable<double> fk { get; set; }
        public Nullable<double> sbr { get; set; }
        public Nullable<double> eg { get; set; }
        public Nullable<double> ak { get; set; }
        public Nullable<double> ail { get; set; }
        public Nullable<double> nc { get; set; }
        public Nullable<double> ag { get; set; }
        public Nullable<double> fu { get; set; }
        public Nullable<double> ah { get; set; }
        public Nullable<double> eb { get; set; }
        public Nullable<double> sc { get; set; }
        public Nullable<double> fmz { get; set; }
        public Nullable<double> sh { get; set; }
        public Nullable<double> ac { get; set; }
        public Nullable<double> av { get; set; }
        public Nullable<double> se { get; set; }
        public Nullable<double> atr { get; set; }
        public Nullable<double> fg { get; set; }
        public Nullable<double> sm { get; set; }
        public Nullable<double> sp { get; set; }
        public Nullable<double> mo { get; set; }
        public Nullable<double> at { get; set; }
        public Nullable<double> su { get; set; }
        public Nullable<double> ap { get; set; }
        public Nullable<double> fe { get; set; }
        public Nullable<double> eu { get; set; }
        public Nullable<double> zz { get; set; }
        public Nullable<double> ee { get; set; }
        public Nullable<double> fa { get; set; }
        public Nullable<double> mr { get; set; }
        public Nullable<double> ain { get; set; }
        public Nullable<double> mn { get; set; }
        public Nullable<double> scl { get; set; }
        public Nullable<double> total { get; set; }
        public Nullable<double> ank { get; set; }
        public Nullable<double> amo { get; set; }
        public Nullable<double> fr { get; set; }
        public Nullable<double> z1 { get; set; }
        public Nullable<double> z2 { get; set; }
        public Nullable<double> z3 { get; set; }
        public Nullable<double> z4 { get; set; }
    }
}
