//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JamZoo.Project.WebSite.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class energy50_db
    {
        public int yr_mnth { get; set; }
        public int row_no1 { get; set; }
        public Nullable<double> eim001 { get; set; }
        public Nullable<double> eim002 { get; set; }
        public Nullable<double> eim003 { get; set; }
        public Nullable<double> eim004 { get; set; }
        public Nullable<double> eim005 { get; set; }
        public Nullable<double> eim006 { get; set; }
        public Nullable<double> eim007 { get; set; }
        public Nullable<double> eim008 { get; set; }
        public Nullable<double> eim009 { get; set; }
        public Nullable<double> eim010 { get; set; }
        public Nullable<double> eim011 { get; set; }
        public Nullable<double> eim012 { get; set; }
        public Nullable<double> eim013 { get; set; }
        public Nullable<double> eim014 { get; set; }
        public Nullable<double> eim015 { get; set; }
        public Nullable<double> eim016 { get; set; }
        public Nullable<double> eim017 { get; set; }
        public Nullable<double> eim018 { get; set; }
        public Nullable<double> eim019 { get; set; }
        public Nullable<double> eim020 { get; set; }
        public Nullable<double> eim021 { get; set; }
        public Nullable<double> eim022 { get; set; }
        public Nullable<double> eim023 { get; set; }
        public Nullable<double> eim024 { get; set; }
        public Nullable<double> eiy001 { get; set; }
        public Nullable<double> eiy002 { get; set; }
        public Nullable<double> eiy003 { get; set; }
        public Nullable<double> eiy004 { get; set; }
        public Nullable<double> eiy005 { get; set; }
        public Nullable<double> eiy006 { get; set; }
        public Nullable<double> eiy007 { get; set; }
        public Nullable<double> eiy008 { get; set; }
        public Nullable<double> eiy009 { get; set; }
        public Nullable<double> eiy010 { get; set; }
        public Nullable<double> eiy011 { get; set; }
        public Nullable<double> eiy012 { get; set; }
        public Nullable<double> eiy013 { get; set; }
        public Nullable<double> eiy014 { get; set; }
        public Nullable<double> eiy015 { get; set; }
        public Nullable<double> eiy016 { get; set; }
        public Nullable<double> eiy017 { get; set; }
        public Nullable<double> eiy018 { get; set; }
        public Nullable<double> eiy019 { get; set; }
        public Nullable<double> eiy020 { get; set; }
        public Nullable<double> eiy021 { get; set; }
        public Nullable<double> eiy022 { get; set; }
        public Nullable<double> eiy023 { get; set; }
        public Nullable<double> eiy024 { get; set; }
        public Nullable<double> eiy025 { get; set; }
        public Nullable<double> eiy026 { get; set; }
        public Nullable<double> eiy027 { get; set; }
        public Nullable<double> eiq001 { get; set; }
        public Nullable<double> eiq002 { get; set; }
        public Nullable<double> eiq003 { get; set; }
        public Nullable<double> eiq004 { get; set; }
        public Nullable<double> eiq005 { get; set; }
        public Nullable<double> eiq006 { get; set; }
        public Nullable<double> eiq007 { get; set; }
        public Nullable<double> eiq008 { get; set; }
        public Nullable<double> eiq009 { get; set; }
        public Nullable<double> eiq010 { get; set; }
        public Nullable<double> eiq011 { get; set; }
        public Nullable<double> eiq012 { get; set; }
        public Nullable<double> eiq013 { get; set; }
        public Nullable<double> eiq014 { get; set; }
        public Nullable<double> eiq015 { get; set; }
        public Nullable<double> eiq016 { get; set; }
        public Nullable<double> eiq017 { get; set; }
        public Nullable<double> eiq018 { get; set; }
        public Nullable<double> eiq019 { get; set; }
        public Nullable<double> eiq020 { get; set; }
        public Nullable<double> eiq021 { get; set; }
        public Nullable<double> eiq022 { get; set; }
        public Nullable<double> eiq023 { get; set; }
        public Nullable<double> eiy101 { get; set; }
        public Nullable<double> eiy102 { get; set; }
        public Nullable<double> eiy103 { get; set; }
        public Nullable<double> eiy104 { get; set; }
        public Nullable<double> eiy105 { get; set; }
        public Nullable<double> eiy106 { get; set; }
        public Nullable<double> eim008y { get; set; }
        public Nullable<double> eim009y { get; set; }
        public Nullable<double> eim024y { get; set; }
        public Nullable<double> eim008q { get; set; }
        public Nullable<double> eim009q { get; set; }
        public Nullable<double> eim024q { get; set; }
    }
}
