//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JamZoo.Project.WebSite.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class energy50
    {
        public int yr_mnth { get; set; }
        public int row_no1 { get; set; }
        public Nullable<double> ei002 { get; set; }
        public Nullable<double> ei003 { get; set; }
        public Nullable<double> ei004 { get; set; }
        public Nullable<double> ei005 { get; set; }
        public Nullable<double> ei007 { get; set; }
        public Nullable<double> ei008 { get; set; }
        public Nullable<double> ei009 { get; set; }
        public Nullable<double> twp_net { get; set; }
    }
}
