//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JamZoo.Project.WebSite.DbContext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<T_Account> T_Account { get; set; }
        public DbSet<T_Account_Role_Mapping> T_Account_Role_Mapping { get; set; }
        public DbSet<T_Permission> T_Permission { get; set; }
        public DbSet<T_Role> T_Role { get; set; }
        public DbSet<T_Role_Permission_Mapping> T_Role_Permission_Mapping { get; set; }
        public DbSet<T_Industry> T_Industry { get; set; }
        public DbSet<T_Thematic> T_Thematic { get; set; }
        public DbSet<T_Banner> T_Banner { get; set; }
        public DbSet<T_Publication_Level3> T_Publication_Level3 { get; set; }
        public DbSet<T_Publication> T_Publication { get; set; }
        public DbSet<energy50> energy50 { get; set; }
        public DbSet<tmp_cc> tmp_cc { get; set; }
        public DbSet<coal50> coal50 { get; set; }
        public DbSet<T_Parent> T_Parent { get; set; }
        public DbSet<T_ChartData> T_ChartData { get; set; }
        public DbSet<T_Flow> T_Flow { get; set; }
        public DbSet<T_Energy> T_Energy { get; set; }
        public DbSet<energy50_db> energy50_db { get; set; }
        public DbSet<wesdes50> wesdes50 { get; set; }
        public DbSet<wesdes50_db> wesdes50_db { get; set; }
        public DbSet<power50_db> power50_db { get; set; }
        public DbSet<T_Child> T_Child { get; set; }
        public DbSet<T_System> T_System { get; set; }
        public DbSet<power50> power50 { get; set; }
        public DbSet<fuel50_db> fuel50_db { get; set; }
        public DbSet<upfile_log> upfile_log { get; set; }
        public DbSet<T_Publication_Level1> T_Publication_Level1 { get; set; }
        public DbSet<T_Publication_Level2> T_Publication_Level2 { get; set; }
    }
}
