//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JamZoo.Project.WebSite.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class power50
    {
        public int yr_mnth { get; set; }
        public int row_no1 { get; set; }
        public Nullable<double> twp_inst { get; set; }
        public Nullable<double> tfc_inst { get; set; }
        public Nullable<double> tfo_inst { get; set; }
        public Nullable<double> tfn_inst { get; set; }
        public Nullable<double> tn_inst { get; set; }
        public Nullable<double> twh_inst { get; set; }
        public Nullable<double> tag_inst { get; set; }
        public Nullable<double> ts_inst { get; set; }
        public Nullable<double> tw_inst { get; set; }
        public Nullable<double> mfc_inst { get; set; }
        public Nullable<double> mfn_inst { get; set; }
        public Nullable<double> mw_inst { get; set; }
        public Nullable<double> mag_inst { get; set; }
        public Nullable<double> ms_inst { get; set; }
        public Nullable<double> ma_inst { get; set; }
        public Nullable<double> afc_inst { get; set; }
        public Nullable<double> afo_inst { get; set; }
        public Nullable<double> afn_inst { get; set; }
        public Nullable<double> awh_inst { get; set; }
        public Nullable<double> aag_inst { get; set; }
        public Nullable<double> as_inst { get; set; }
        public Nullable<double> aw_inst { get; set; }
        public Nullable<double> abiom_inst { get; set; }
        public Nullable<double> awast_inst { get; set; }
        public Nullable<double> towp_inst { get; set; }
        public Nullable<double> tofc_inst { get; set; }
        public Nullable<double> tofo_inst { get; set; }
        public Nullable<double> tofn_inst { get; set; }
        public Nullable<double> ton_inst { get; set; }
        public Nullable<double> towh_inst { get; set; }
        public Nullable<double> toag_inst { get; set; }
        public Nullable<double> tos_inst { get; set; }
        public Nullable<double> tow_inst { get; set; }
        public Nullable<double> tobiom_inst { get; set; }
        public Nullable<double> towast_inst { get; set; }
        public Nullable<double> twp_net { get; set; }
        public Nullable<double> twp_st { get; set; }
        public Nullable<double> tfc_net { get; set; }
        public Nullable<double> tfc_st { get; set; }
        public Nullable<double> mfc_net { get; set; }
        public Nullable<double> mfc_st { get; set; }
        public Nullable<double> a_coal { get; set; }
        public Nullable<double> tfo_net { get; set; }
        public Nullable<double> tfo_s { get; set; }
        public Nullable<double> a_oil { get; set; }
        public Nullable<double> tfn_net { get; set; }
        public Nullable<double> tfn_st { get; set; }
        public Nullable<double> mfn_net { get; set; }
        public Nullable<double> mfn_st { get; set; }
        public Nullable<double> tn_net { get; set; }
        public Nullable<double> tn_st { get; set; }
        public Nullable<double> twh_net { get; set; }
        public Nullable<double> twh_st { get; set; }
        public Nullable<double> mw_net { get; set; }
        public Nullable<double> mw_st { get; set; }
        public Nullable<double> a_hydro { get; set; }
        public Nullable<double> tag_net { get; set; }
        public Nullable<double> tag_st { get; set; }
        public Nullable<double> mg_net { get; set; }
        public Nullable<double> mg_st { get; set; }
        public Nullable<double> a_geot { get; set; }
        public Nullable<double> ts_net { get; set; }
        public Nullable<double> ts_st { get; set; }
        public Nullable<double> ms_net { get; set; }
        public Nullable<double> ms_st { get; set; }
        public Nullable<double> a_sun { get; set; }
        public Nullable<double> taw_net { get; set; }
        public Nullable<double> taw_st { get; set; }
        public Nullable<double> ma_net { get; set; }
        public Nullable<double> ma_st { get; set; }
        public Nullable<double> a_wind { get; set; }
        public Nullable<double> a_biom { get; set; }
        public Nullable<double> a_wast { get; set; }
        public Nullable<double> tfo_st { get; set; }
        public Nullable<double> a_ng { get; set; }
        public Nullable<double> taw_inst { get; set; }
        public Nullable<double> mg_inst { get; set; }
        public Nullable<double> a_coal_inst { get; set; }
        public Nullable<double> a_oil_inst { get; set; }
        public Nullable<double> a_ng_inst { get; set; }
        public Nullable<double> a_hydro_inst { get; set; }
        public Nullable<double> a_geot_inst { get; set; }
        public Nullable<double> a_sun_inst { get; set; }
        public Nullable<double> a_wind_inst { get; set; }
        public Nullable<double> a_biom_inst { get; set; }
        public Nullable<double> a_wast_inst { get; set; }
        public Nullable<double> mwh_inst { get; set; }
    }
}
