//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JamZoo.Project.WebSite.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class power50_db
    {
        public int yr_mnth { get; set; }
        public int row_no1 { get; set; }
        public Nullable<double> twp_net { get; set; }
        public Nullable<double> twp_st { get; set; }
        public Nullable<double> tfc_net { get; set; }
        public Nullable<double> tfc_st { get; set; }
        public Nullable<double> tfo_net { get; set; }
        public Nullable<double> tfo_st { get; set; }
        public Nullable<double> tfn_net { get; set; }
        public Nullable<double> tfn_st { get; set; }
        public Nullable<double> tn_net { get; set; }
        public Nullable<double> tn_st { get; set; }
        public Nullable<double> twh_net { get; set; }
        public Nullable<double> twh_st { get; set; }
        public Nullable<double> tag_net { get; set; }
        public Nullable<double> tag_st { get; set; }
        public Nullable<double> ts_net { get; set; }
        public Nullable<double> ts_st { get; set; }
        public Nullable<double> tw_net { get; set; }
        public Nullable<double> tw_st { get; set; }
        public Nullable<double> mfc_net { get; set; }
        public Nullable<double> mfc_st { get; set; }
        public Nullable<double> mfn_net { get; set; }
        public Nullable<double> mfn_st { get; set; }
        public Nullable<double> mwh_net { get; set; }
        public Nullable<double> mwh_st { get; set; }
        public Nullable<double> mag_net { get; set; }
        public Nullable<double> mag_st { get; set; }
        public Nullable<double> ms_net { get; set; }
        public Nullable<double> ms_st { get; set; }
        public Nullable<double> mw_net { get; set; }
        public Nullable<double> mw_st { get; set; }
        public Nullable<double> afc { get; set; }
        public Nullable<double> afo { get; set; }
        public Nullable<double> afn { get; set; }
        public Nullable<double> awh { get; set; }
        public Nullable<double> aag { get; set; }
        public Nullable<double> @as { get; set; }
        public Nullable<double> aw { get; set; }
        public Nullable<double> abiom { get; set; }
        public Nullable<double> awast { get; set; }
        public Nullable<double> twp { get; set; }
        public Nullable<double> tfc { get; set; }
        public Nullable<double> tfo { get; set; }
        public Nullable<double> tfn { get; set; }
        public Nullable<double> tn { get; set; }
        public Nullable<double> twh { get; set; }
        public Nullable<double> tag { get; set; }
        public Nullable<double> ms { get; set; }
        public Nullable<double> tw { get; set; }
        public Nullable<double> mfc { get; set; }
        public Nullable<double> mfn { get; set; }
        public Nullable<double> mwh { get; set; }
        public Nullable<double> mag { get; set; }
        public Nullable<double> mw { get; set; }
        public Nullable<double> towp { get; set; }
        public Nullable<double> tofc { get; set; }
        public Nullable<double> tofo { get; set; }
        public Nullable<double> tofn { get; set; }
        public Nullable<double> ton { get; set; }
        public Nullable<double> towh { get; set; }
        public Nullable<double> toag { get; set; }
        public Nullable<double> tos { get; set; }
        public Nullable<double> tow { get; set; }
        public Nullable<double> tobiom { get; set; }
        public Nullable<double> towast { get; set; }
        public Nullable<double> ts { get; set; }
    }
}
