//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JamZoo.Project.WebSite.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Child
    {
        public string Id { get; set; }
        public string SelfId { get; set; }
        public int IndustryId { get; set; }
        public string ParentId { get; set; }
        public string Name { get; set; }
        public int IOrder { get; set; }
        public string IndustryIds { get; set; }
        public string ColumnIdAll { get; set; }
        public string ColumnId1 { get; set; }
        public string ColumnId2 { get; set; }
        public string ColumnId3 { get; set; }
        public string ColumnId4 { get; set; }
        public string ColumnId5 { get; set; }
        public string ColumnId6 { get; set; }
        public string ColumnId7 { get; set; }
        public string ColumnId8 { get; set; }
        public string ColumnId9 { get; set; }
        public string ColumnId10 { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UnitList { get; set; }
        public string AltName { get; set; }
        public int DecimalPlaces { get; set; }
    }
}
