//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JamZoo.Project.WebSite.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Energy
    {
        public string Id { get; set; }
        public string PageName { get; set; }
        public string ParentId { get; set; }
        public Nullable<int> Depth { get; set; }
        public string Name { get; set; }
        public string TableName { get; set; }
        public string UnitListUpper { get; set; }
        public string UnitListBottom { get; set; }
        public string ColIdList { get; set; }
        public string Notes { get; set; }
        public string HideList { get; set; }
        public string ColorList { get; set; }
        public int IOrder { get; set; }
        public string row_no1 { get; set; }
    }
}
